name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_rounded_progress_bar: 0.1.1
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_speed_dial: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/dreamcatcher.png

  fonts:
    - family: Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

